# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.14.1-11-g1dfbdeb
_src_path: gh:tsvikas/python-template
format_tool: black
get_package_version_from_vcs: true
github_user: tsvikas
has_cli: false
jupyter_files: forbid
license: MIT
package_description: Ray tracing from scratch with PyTorch for educational and illustrative
    purposes.
package_name: raytrace
project_name: torch-raytrace
python_min: 13
user_email: tsvikas@gmail.com
user_name: Tsvika Shapira
year: 2025
